=== iconmaster5326/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of locales to textual card information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "enum": [
              "unlimited",
              "semilimited",
              "limited",
              "forbidden",
              "limit1",
              "limit2",
              "limit3",
              "unreleased"
            ]
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "description": "What the legality was changed to.",
                  "enum": [
                    "unlimited",
                    "semilimited",
                    "limited",
                    "forbidden",
                    "limit1",
                    "limit2",
                    "limit3"
                  ]
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page.",
          "type": "string"
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== iconmaster5326/YGOJSON/cards/c4a0923a-914c-4b78-85d4-725ebb2632aa.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "c4a0923a-914c-4b78-85d4-725ebb2632aa",
  "text": {
    "en": {
      "name": "Mimighoul Throne",
      "official": false
    },
    "fr": {
      "name": "Tr\u00f4ne Mimigoule",
      "effect": "2 monstres \"Mimigoule\" de Niveau 1\nVous pouvez d\u00e9tacher 1 Mat\u00e9riel de cette carte ; Invoquez Sp\u00e9cialement 1 \"Ma\u00eetre Mimigoule\" depuis votre main, Deck ou Cimeti\u00e8re. Durant la Main Phase (Effet Rapide) : vous pouvez cibler 1 \"Ma\u00eetre Mimigoule\" que vous contr\u00f4lez ; \u00e9quipez-lui cette carte comme Magie d'\u00c9quipement qui lui donne 1000 ATK, puis vous pouvez renvoyer un nombre de cartes depuis le Terrain \u00e0 la main, inf\u00e9rieur ou \u00e9gal au nombre de Mat\u00e9riels que cette carte avait. Vous ne pouvez utiliser qu'1 effet de \"Tr\u00f4ne Mimigoule\" par tour, et uniquement une fois le tour."
    },
    "de": {
      "name": "Mimighul Thron",
      "effect": "2 \u201eMimighul\u201c-Monster der Stufe 1\nDu kannst 1 Material von dieser Karte abh\u00e4ngen; beschw\u00f6re 1 \u201eMimighul Meister\u201c als Spezialbeschw\u00f6rung von deiner Hand, deinem Deck oder deinem Friedhof. W\u00e4hrend der Main Phase (Schnelleffekt): Du kannst 1 \u201eMimighul Meister\u201c w\u00e4hlen, den du kontrollierst; r\u00fcste ihn mit dieser Karte als Ausr\u00fcstungszauber aus, der ihm 1000 ATK gibt, dann kannst du Karten vom Spielfeld bis zur Anzahl des Materials, das diese Karte hatte, auf die Hand zur\u00fcckgeben. Du kannst nur 1 Effekt von \u201eMimighul Thron\u201c pro Spielzug verwenden und in jenem Spielzug nur einmal."
    },
    "it": {
      "name": "Mimighoul Trono",
      "effect": "2 mostri \"Mimighoul\" di Livello 1\nPuoi staccare 1 materiale da questa carta; Evoca Specialmente 1 \"Mimighoul Maestro\" dalla tua mano, Deck o Cimitero. Durante la Main Phase (Effetto Rapido): puoi scegliere come bersaglio 1 \"Mimighoul Maestro\" che controlli; equipaggia questa carta a esso come una Magia Equipaggiamento che gli d\u00e0 1000 ATK, poi puoi far ritornare carte dal Terreno nella mano, fino al numero di materiali che questa carta aveva. Puoi utilizzare solo 1 effetto di \"Mimighoul Trono\" per turno, e solo una volta in quel turno."
    },
    "pt": {
      "name": "Trono Mimicarni\u00e7al",
      "effect": "2 monstros \"Mimicarni\u00e7al\" de N\u00edvel 1\nVoc\u00ea pode desassociar 1 mat\u00e9ria deste card; Invoque por Invoca\u00e7\u00e3o-Especial 1 \"Mestre Mimicarni\u00e7al\" da sua m\u00e3o, do Deck ou do Cemit\u00e9rio. Durante a Fase Principal (Efeito R\u00e1pido): voc\u00ea pode escolher 1 \"Mestre Mimicarni\u00e7al\" que voc\u00ea controla; equipe este card a ele como uma Magia de Equipamento que concede a ele 1000 de ATK e, depois, voc\u00ea pode devolver cards do campo para a m\u00e3o, at\u00e9 o n\u00famero de mat\u00e9rias que este card tinha. Voc\u00ea s\u00f3 pode usar 1 efeito de \"Trono Mimicarni\u00e7al\" por turno e apenas uma vez por turno."
    },
    "es": {
      "name": "Trono Mimighoul",
      "effect": "2 monstruos \"Mimighoul\" de Nivel 1\nPuedes desacoplar 1 material de esta carta; Invoca de Modo Especial, desde tu mano, Deck o Cementerio, 1 \"M\u00e1ster Mimighoul\". Durante la Main Phase (Efecto R\u00e1pido): puedes seleccionar 1 \"M\u00e1ster Mimighoul\" que controles; equ\u00edpale esta carta como una M\u00e1gica de Equipo que le da 1000 ATK, y despu\u00e9s puedes devolver cartas del Campo a la mano, hasta el n\u00famero de materiales que ten\u00eda esta carta. S\u00f3lo puedes usar 1 efecto de \"Trono Mimighoul\" por turno, y s\u00f3lo una vez ese turno."
    }
  },
  "cardType": "monster",
  "attribute": "earth",
  "monsterCardTypes": [
    "xyz"
  ],
  "type": "rock",
  "classifications": [
    "effect"
  ],
  "rank": 1,
  "atk": 0,
  "def": 1000,
  "passwords": [],
  "images": [
    {
      "id": "a7b155de-185a-47c1-aa79-f144b83acf39",
      "card": "https://ms.yugipedia.com//a/a9/MimighoulThrone-ROTA-EN-1E-OP.png"
    },
    {
      "id": "88ef2c8c-ba6d-4f0f-a187-08abff65a316",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/101206094.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/101206094.jpg"
    }
  ],
  "sets": [
    "da514056-29d5-423d-92ce-0e77ebd8b4c3",
    "da514056-29d5-423d-92ce-0e77ebd8b4c3",
    "da514056-29d5-423d-92ce-0e77ebd8b4c3",
    "da514056-29d5-423d-92ce-0e77ebd8b4c3"
  ],
  "legality": {},
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Mimighoul Throne",
        "id": 1083514
      }
    ],
    "ygoprodeck": {
      "id": 101206094,
      "name": "mimighoul-throne-14745"
    }
  },
  "series": [
    "fe7bedf0-5ce5-4a1b-8384-2b6d99f39858"
  ]
}

=== iconmaster5326/YGOJSON/cards/7ae6b3bf-9cda-4fe7-a161-c7f895a69800.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "7ae6b3bf-9cda-4fe7-a161-c7f895a69800",
  "text": {
    "en": {
      "name": "Unity",
      "effect": "Select 1 monster on your side of the field. The DEF of the selected monster becomes equal to the combined original DEF of all face-up monsters on your side of the field, until the end of this turn."
    },
    "de": {
      "name": "Einheit",
      "effect": "W\u00e4hle ein Monster auf deinem Feld aus. Der DEF dieses Monsters wird zur Summe der urspr\u00fcnglichen DEF-Werte aller aufgedeckten Monster auf deinem Feld, bis deine End Phase beginnt."
    },
    "es": {
      "name": "Unidad",
      "effect": "Selecciona un Monstruo en tu campo. El DEF del Monstruo seleccionado pasa a ser la suma del DEF original de todos los Monstruos boca arriba en tu campo hasta tu End Phase."
    },
    "fr": {
      "name": "Alliance",
      "effect": "Choisissez un monstre sur votre Terrain. Les Points DEF de ce monstre deviennent la somme de tous les Points DEF des monstres pos\u00e9s face recto sur votre Terrain jusqu'\u00e0 votre End Phase."
    },
    "it": {
      "name": "Unit\u00e0",
      "effect": "Seleziona un Mostro presente nella tua parte di Campo. Fino alla tua End Phase, il valore DEF del Mostro selezionato diviene pari alla somma dei valori DEF di tutti i Mostri presenti scoperti nella tua parte di Campo."
    },
    "pt": {
      "name": "Unidade",
      "effect": "Selecione 1 monstro no seu lado do campo. A DEF do monstro selecionado se torna igual \u00e0 DEF original combinada de todos os monstros com a face para cima no seu lado do campo at\u00e9 o fim deste turno."
    },
    "ja": {
      "name": "\u7d50\u675f \uff35\uff2e\uff29\uff34\uff39",
      "effect": "\u2460\uff1a\u81ea\u5206\u30d5\u30a3\u30fc\u30eb\u30c9\u306e\u8868\u5074\u8868\u793a\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\u5bfe\u8c61\u3068\u3057\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u305d\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u5b88\u5099\u529b\u306f\u30bf\u30fc\u30f3\u7d42\u4e86\u6642\u307e\u3067\u3001\u81ea\u5206\u30d5\u30a3\u30fc\u30eb\u30c9\u306e\u5168\u3066\u306e\u8868\u5074\u8868\u793a\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u5143\u3005\u306e\u5b88\u5099\u529b\u3092\u5408\u8a08\u3057\u305f\u6570\u5024\u306b\u306a\u308b\u3002"
    },
    "ko": {
      "name": "\uacb0\uc18d UNITY",
      "effect": "\uc790\uc2e0\uc758 \ud544\ub4dc \uc704 \ubaac\uc2a4\ud130 1\uc7a5\uc744 \uc120\ud0dd\ud55c\ub2e4. \uc120\ud0dd\ud55c \ubaac\uc2a4\ud130\uc758 \uc218\ube44\ub825\uc740 \uc5d4\ub4dc \ud398\uc774\uc988\uae4c\uc9c0, \uc790\uc2e0\uc758 \ud544\ub4dc \uc704\uc5d0 \uc55e\uba74 \ud45c\uc2dc\ub85c \uc874\uc7ac\ud558\ub294 \ubaac\uc2a4\ud130 \uc804\ubd80\uc758 \uc6d0\ub798 \uc218\ube44\ub825\uc744 \ud569\uacc4\ud55c \uc218\uce58\uac00 \ub41c\ub2e4."
    },
    "zh-TW": {
      "name": "\u5718\u7d50 UNITY",
      "effect": "\u2460\uff1a\u53ef\u5c07\u6211\u65b9\u5834\u4e0a\u7684\uff11\u96bb\u6b63\u9762\u8868\u793a\u602a\u7378\u505a\u70ba\u5c0d\u8c61\u767c\u52d5\u3002\u8a72\u602a\u7378\u7684\u5b88\u5099\u529b\u5728\u56de\u5408\u7d50\u675f\u524d\uff0c\u8b8a\u70ba\u6211\u65b9\u5834\u4e0a\u6240\u6709\u6b63\u9762\u8868\u793a\u602a\u7378\u539f\u672c\u7684\u5b88\u5099\u529b\u7684\u5408\u8a08\u6578\u503c\u3002"
    },
    "zh-CN": {
      "name": "\u56e2\u7ed3 UNITY",
      "effect": "\u2460\uff1a\u4ee5\u81ea\u5df1\u573a\u4e0a1\u53ea\u8868\u4fa7\u8868\u793a\u602a\u517d\u4e3a\u5bf9\u8c61\u624d\u80fd\u53d1\u52a8\u3002\u90a3\u53ea\u602a\u517d\u7684\u5b88\u5907\u529b\u76f4\u5230\u56de\u5408\u7ed3\u675f\u65f6\u53d8\u6210\u81ea\u5df1\u573a\u4e0a\u7684\u5168\u90e8\u8868\u4fa7\u8868\u793a\u602a\u517d\u7684\u539f\u672c\u5b88\u5907\u529b\u5408\u8ba1\u6570\u503c\u3002"
    }
  },
  "cardType": "spell",
  "subcategory": "quickplay",
  "passwords": [
    "14731897"
  ],
  "images": [
    {
      "id": "ec309b5b-1715-4a25-a32a-d27487b6fe2f",
      "password": "14731897",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/14731897.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/14731897.jpg"
    }
  ],
  "sets": [
    "1882a77f-cdd2-4a2a-aba3-d5f786f52ded",
    "69b2fdc7-344c-4c00-8a3e-5ce8581a980c",
    "11f18aea-bdcf-462c-aedc-c83e68730902",
    "b650d14c-d74e-4674-b326-a7045b624ec6",
    "ec8720af-4bf6-41da-91a9-21ec1a4f1ea5",
    "166ee89f-e6fc-4642-b6b1-c5efc6db4873"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "ur",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "ur"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Unity",
        "id": 7406
      }
    ],
    "dbID": 5755,
    "ygoprodeck": {
      "id": 14731897,
      "name": "unity-1259"
    },
    "yamlyugiID": 14731897
  },
  "series": []
}
