=== iconmaster5326/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of locales to textual card information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "enum": [
              "unlimited",
              "semilimited",
              "limited",
              "forbidden",
              "limit1",
              "limit2",
              "limit3",
              "unreleased"
            ]
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "description": "What the legality was changed to.",
                  "enum": [
                    "unlimited",
                    "semilimited",
                    "limited",
                    "forbidden",
                    "limit1",
                    "limit2",
                    "limit3"
                  ]
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page.",
          "type": "string"
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== iconmaster5326/YGOJSON/cards/912364c8-8a40-4d4f-96bc-f204d039b580.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "912364c8-8a40-4d4f-96bc-f204d039b580",
  "text": {
    "en": {
      "name": "Gogogo Giant",
      "official": false
    },
    "de": {
      "name": "Gogogo-Riese",
      "effect": "Wenn diese Karte als Normalbeschw\u00f6rung beschworen wird: Du kannst 1 \u201eGogogo\u201c-Monster in deinem Friedhof w\u00e4hlen; beschw\u00f6re das gew\u00e4hlte Ziel als Spezialbeschw\u00f6rung in die Verteidigungsposition, dann \u00e4ndere diese Karte in die Verteidigungsposition. Falls diese Karte angreift, wird sie am Ende der Battle Phase in die Verteidigungsposition ge\u00e4ndert."
    },
    "es": {
      "name": "Gigante Gogogo",
      "effect": "Cuando esta carta es Invocada de Modo Normal: puedes seleccionar 1 monstruo \"Gogogo\" en tu Cementerio; Invoca ese objetivo de Modo Especial en Posici\u00f3n de Defensa, y despu\u00e9s cambia esta carta a Posici\u00f3n de Defensa. Si esta carta ataca, se cambia a Posici\u00f3n de Defensa al final de la Battle Phase."
    },
    "fr": {
      "name": "G\u00e9ant Gogogo",
      "effect": "Lorsque cette carte est Invoqu\u00e9e Normalement : vous pouvez cibler 1 monstre \"Gogogo\" dans votre Cimeti\u00e8re ; Invoquez Sp\u00e9cialement la cible en Position de D\u00e9fense, puis changez cette carte en Position de D\u00e9fense. Si cette carte attaque, elle est chang\u00e9e en Position de D\u00e9fense \u00e0 la fin de la Battle Phase."
    },
    "it": {
      "name": "Gigante Gogogo",
      "effect": "Quando questa carta viene Evocata Normalmente: puoi scegliere come bersaglio 1 mostro \"Gogogo\" nel tuo Cimitero; Evoca Specialmente quel bersaglio in Posizione di Difesa, poi metti questa carta in Posizione di Difesa. Se questa carta attacca, essa viene messa in Posizione di Difesa alla fine della Battle Phase."
    },
    "pt": {
      "name": "Gigante Gogogo",
      "effect": "Quando este card for Invocado por Invoca\u00e7\u00e3o-Normal: voc\u00ea pode escolher 1 monstro \"Gogogo\" no seu Cemit\u00e9rio; Invoque o alvo por Invoca\u00e7\u00e3o-Especial em Posi\u00e7\u00e3o de Defesa e, depois, coloque este card em Posi\u00e7\u00e3o de Defesa. Se este card atacar, ele \u00e9 colocado em Posi\u00e7\u00e3o de Defesa no final da Fase de Batalha."
    },
    "ja": {
      "name": "\u30b4\u30b4\u30b4\u30b8\u30e3\u30a4\u30a2\u30f3\u30c8",
      "effect": "\u2460\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u304c\u53ec\u559a\u306b\u6210\u529f\u3057\u305f\u6642\u3001\u81ea\u5206\u306e\u5893\u5730\u306e\u300c\u30b4\u30b4\u30b4\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u4f53\u3092\u5bfe\u8c61\u3068\u3057\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u305d\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u3092\u5b88\u5099\u8868\u793a\u3067\u7279\u6b8a\u53ec\u559a\u3059\u308b\u3002\u305d\u306e\u5f8c\u3001\u3053\u306e\u30ab\u30fc\u30c9\u306f\u5b88\u5099\u8868\u793a\u306b\u306a\u308b\u3002\u2461\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u306f\u653b\u6483\u3057\u305f\u5834\u5408\u3001\u30d0\u30c8\u30eb\u30d5\u30a7\u30a4\u30ba\u7d42\u4e86\u6642\u306b\u5b88\u5099\u8868\u793a\u306b\u306a\u308b\u3002"
    },
    "ko": {
      "name": "\uace0\uace0\uace0 \uc790\uc774\uc5b8\ud2b8",
      "effect": "\u2460: \uc774 \uce74\ub4dc\uac00 \uc77c\ubc18 \uc18c\ud658\uc5d0 \uc131\uacf5\ud588\uc744 \ub54c, \uc790\uc2e0 \ubb18\uc9c0\uc758 \"\uace0\uace0\uace0\" \ubaac\uc2a4\ud130 1\uc7a5\uc744 \ub300\uc0c1\uc73c\ub85c \ud558\uace0 \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \uadf8 \ubaac\uc2a4\ud130\ub97c \uc218\ube44 \ud45c\uc2dc\ub85c \ud2b9\uc218 \uc18c\ud658\ud55c\ub2e4. \uadf8 \ud6c4, \uc774 \uce74\ub4dc\ub294 \uc218\ube44 \ud45c\uc2dc\uac00 \ub41c\ub2e4. \u2461: \uc774 \uce74\ub4dc\ub294 \uacf5\uaca9\ud588\uc744 \uacbd\uc6b0, \ubc30\ud2c0 \ud398\uc774\uc988 \uc885\ub8cc\uc2dc\uc5d0 \uc218\ube44 \ud45c\uc2dc\uac00 \ub41c\ub2e4."
    },
    "zh-TW": {
      "name": "\u9686\u9686\u9686\u5de8\u4eba",
      "effect": "\u6b64\u5361\u53ec\u5524\u6210\u529f\u65f6\uff0c\u53ef\u9009\u62e9\u6211\u65b9\u5893\u57301\u53ea\u51a0\u6709\u300c\u9686\u9686\u9686\u300d\u540d\u79f0\u7684\u602a\u517d\uff0c\u5e76\u4e8e\u8868\u4fa7\u5b88\u5907\u8868\u793a\u8fdb\u884c\u7279\u522b\u53ec\u5524\u3002\u4e4b\u540e\uff0c\u6b64\u5361\u8f6c\u4e3a\u5b88\u5907\u8868\u793a\u3002\u53e6\u5916\uff0c\u6b64\u5361\u82e5\u8fdb\u884c\u4e86\u653b\u51fb\uff0c\u5728\u6218\u6597\u9636\u6bb5\u7ed3\u675f\u65f6\u5c06\u8f6c\u4e3a\u5b88\u5907\u8868\u793a\u3002"
    },
    "zh-CN": {
      "name": "\u9686\u9686\u9686\u5de8\u4eba",
      "effect": "\u2460\uff1a\u6b64\u5361\u53ec\u5524\u6210\u529f\u65f6\uff0c\u4ee5\u81ea\u5df1\u5893\u5730\u7684\uff11\u53ea\u201c\u9686\u9686\u9686\u201d\u602a\u517d\u4e3a\u5bf9\u8c61\u53ef\u4ee5\u53d1\u52a8\u3002\u4ee5\u5b88\u5907\u8868\u793a\u5f62\u5f0f\u5c06\u8be5\u602a\u517d\u7279\u6b8a\u53ec\u5524\u3002\u7136\u540e\u6b64\u5361\u53d8\u4e3a\u5b88\u5907\u8868\u793a\u3002\u2461\uff1a\u6b64\u5361\u653b\u51fb\u7684\u60c5\u51b5\u4e0b\uff0c\u6218\u6597\u9636\u6bb5\u7ed3\u675f\u65f6\u53d8\u4e3a\u5b88\u5907\u8868\u793a\u3002"
    }
  },
  "cardType": "monster",
  "attribute": "earth",
  "type": "rock",
  "classifications": [
    "effect"
  ],
  "level": 4,
  "atk": 2000,
  "def": 0,
  "passwords": [
    "39695323"
  ],
  "images": [
    {
      "id": "c8976d8a-3047-4502-ae6a-366abd29d946",
      "password": "39695323",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/39695323.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/39695323.jpg"
    }
  ],
  "sets": [
    "a7649aac-46ac-4d78-bf79-cab4c849ff6e",
    "a7649aac-46ac-4d78-bf79-cab4c849ff6e",
    "a7649aac-46ac-4d78-bf79-cab4c849ff6e",
    "a7649aac-46ac-4d78-bf79-cab4c849ff6e",
    "a7649aac-46ac-4d78-bf79-cab4c849ff6e",
    "a7649aac-46ac-4d78-bf79-cab4c849ff6e",
    "7db0c394-f18c-4364-ac02-598a32c1b67e",
    "7db0c394-f18c-4364-ac02-598a32c1b67e",
    "7db0c394-f18c-4364-ac02-598a32c1b67e",
    "7db0c394-f18c-4364-ac02-598a32c1b67e",
    "7db0c394-f18c-4364-ac02-598a32c1b67e",
    "7db0c394-f18c-4364-ac02-598a32c1b67e",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "20b22e3a-b52c-41ed-920a-787ff7e7073b",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "4cf4c3ee-d28c-4992-b908-63f97dcf3f74",
    "8d6bd298-3ef1-4965-bb1d-45fb970d8e9a",
    "8d6bd298-3ef1-4965-bb1d-45fb970d8e9a",
    "8d6bd298-3ef1-4965-bb1d-45fb970d8e9a",
    "8d6bd298-3ef1-4965-bb1d-45fb970d8e9a",
    "8d6bd298-3ef1-4965-bb1d-45fb970d8e9a",
    "d1ccd627-230c-4f05-9e0e-eaf8553e584e",
    "2ce4f1b7-ab57-477b-9c7b-eee2fb0b9b5d",
    "2ce4f1b7-ab57-477b-9c7b-eee2fb0b9b5d",
    "13500ddd-9d30-46f6-8e07-03532a7d3d39",
    "13500ddd-9d30-46f6-8e07-03532a7d3d39",
    "8ac90ec2-3330-43ab-8a7a-61bea7474144",
    "8ac90ec2-3330-43ab-8a7a-61bea7474144",
    "4c5e178b-e4d9-43fb-85d7-85ed02ce473d",
    "8647dd93-5460-442f-84e6-26dd6022fed0",
    "ef36aa55-e6b8-41ea-af9e-4a63da5f147e",
    "c37e37c3-7a04-45d6-9155-7975291020ee",
    "9890b3f7-abfc-414c-9bd1-347f2e5c7fba"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "sr",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "r"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Gogogo Giant",
        "id": 193339
      }
    ],
    "dbID": 9878,
    "ygoprodeck": {
      "id": 39695323,
      "name": "gogogo-giant-3361"
    },
    "yamlyugiID": 39695323
  },
  "series": [
    "26033d34-7056-45de-a10e-77f81cc3d1f5"
  ]
}

=== iconmaster5326/YGOJSON/cards/507afda0-de1e-4d93-a931-3de7994482b0.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "507afda0-de1e-4d93-a931-3de7994482b0",
  "text": {
    "en": {
      "name": "Warm Worm",
      "official": false
    },
    "de": {
      "name": "Warmer Wurm",
      "effect": "Falls diese Karte zerst\u00f6rt wird, lege die obersten 3 Karten vom Deck deines Gegners auf den Friedhof."
    },
    "es": {
      "name": "Gusano Ardiente",
      "effect": "Si esta carta es destruida, manda al Cementerio a las 3 cartas de la parte superior del Deck de tu adversario."
    },
    "fr": {
      "name": "Ver de Feu",
      "effect": "Si cette carte est d\u00e9truite, envoyez les 3 cartes du dessus du Deck de votre adversaire au Cimeti\u00e8re."
    },
    "it": {
      "name": "Verme Ardente",
      "effect": "Se questa carta viene distrutta, manda 3 carte del Deck del tuo avversario al Cimitero."
    },
    "pt": {
      "name": "Lombriga Ardente",
      "effect": "Se este card for destru\u00eddo, envie os 3 cards do topo do Deck do oponente para o Cemit\u00e9rio."
    },
    "ja": {
      "name": "\u30a6\u30a9\u30fc\u30e0\u30fb\u30ef\u30fc\u30e0",
      "effect": "\u2460\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u304c\u7834\u58ca\u3055\u308c\u305f\u5834\u5408\u306b\u767a\u52d5\u3059\u308b\u3002\u76f8\u624b\u306e\u30c7\u30c3\u30ad\u306e\u4e0a\u304b\u3089\u30ab\u30fc\u30c9\u3092\uff13\u679a\u5893\u5730\u3078\u9001\u308b\u3002"
    },
    "ko": {
      "name": "\uc6b0\uc634 \uc6dc",
      "effect": "\uc774 \uce74\ub4dc\uac00 \ud30c\uad34\ub418\uc5c8\uc744 \uacbd\uc6b0, \uc0c1\ub300\uc758 \ub371 \uc704\uc5d0\uc11c \uce74\ub4dc\ub97c 3\uc7a5 \ubb18\uc9c0\ub85c \ubcf4\ub0b8\ub2e4."
    },
    "zh-TW": {
      "name": "\u6696\u7570\u87f2",
      "effect": "\u2460\uff1a\u5728\u6b64\u5361\u88ab\u7834\u58de\u7684\u72c0\u6cc1\u4e0b\u767c\u52d5\u3002\u5f9e\u5c0d\u65b9\u724c\u7d44\u4e0a\u65b9\u5c07\uff13\u5f35\u5361\u9001\u81f3\u5893\u5730\u3002"
    },
    "zh-CN": {
      "name": "\u6696\u866b",
      "effect": "\u2460\uff1a\u8fd9\u5f20\u5361\u88ab\u7834\u574f\u7684\u573a\u5408\u53d1\u52a8\u3002\u4ece\u5bf9\u65b9\u5361\u7ec4\u4e0a\u9762\u628a3\u5f20\u5361\u9001\u53bb\u5893\u5730\u3002"
    }
  },
  "cardType": "monster",
  "attribute": "fire",
  "type": "insect",
  "classifications": [
    "effect"
  ],
  "level": 3,
  "atk": 600,
  "def": 1400,
  "passwords": [
    "16751086"
  ],
  "images": [
    {
      "id": "3328e945-165f-409e-b0c7-ec480c01675f",
      "password": "16751086",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/16751086.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/16751086.jpg"
    }
  ],
  "sets": [
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "eee52c01-808d-4796-bb87-f18c2d134843",
    "1834d6ae-ba04-4cb4-b15a-cd08c8f8aacb",
    "744d6edc-439a-4817-955b-3df1fa1a7ecf"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "r",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "sr"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Warm Worm",
        "id": 48242
      }
    ],
    "dbID": 8517,
    "ygoprodeck": {
      "id": 16751086,
      "name": "warm-worm-1441"
    },
    "yamlyugiID": 16751086
  },
  "series": [
    "6184491c-679a-4951-bb46-52bde1714507"
  ]
}
