=== iconmaster5326/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of locales to textual card information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "enum": [
              "unlimited",
              "semilimited",
              "limited",
              "forbidden",
              "limit1",
              "limit2",
              "limit3",
              "unreleased"
            ]
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "description": "What the legality was changed to.",
                  "enum": [
                    "unlimited",
                    "semilimited",
                    "limited",
                    "forbidden",
                    "limit1",
                    "limit2",
                    "limit3"
                  ]
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page.",
          "type": "string"
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== iconmaster5326/YGOJSON/cards/991b6004-d82d-4d40-9960-720bec05dff1.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "991b6004-d82d-4d40-9960-720bec05dff1",
  "text": {
    "en": {
      "name": "Dealer's Choice",
      "official": false
    },
    "de": {
      "name": "Wahl des Gebers",
      "effect": "Jeder Spieler mischt sein Deck, dann zieht jeder Spieler 1 Karte, dann wirft jeder Spieler 1 Karte ab."
    },
    "es": {
      "name": "Elecci\u00f3n del Repartidor",
      "effect": "Cada jugador baraja su Deck, y despu\u00e9s cada jugador roba 1 carta, y despu\u00e9s cada jugador descarta 1 carta."
    },
    "fr": {
      "name": "Choix du Donneur",
      "effect": "Chaque joueur m\u00e9lange son Deck, puis chaque joueur pioche 1 carte, puis chaque joueur d\u00e9fausse 1 carte."
    },
    "it": {
      "name": "Scelta del Banco",
      "effect": "Ogni giocatore mischia il suo Deck, poi ogni giocatore pesca 1 carta, poi ogni giocatore scarta 1 carta."
    },
    "pt": {
      "name": "Escolha do Carteador",
      "effect": "Cada duelista embaralha seu Deck e, depois, cada duelista compra 1 card e, depois, cada duelista descarta 1 card."
    },
    "ja": {
      "name": "\u30c7\u30a3\u30fc\u30e9\u30fc\u30ba\u30fb\u30c1\u30e7\u30a4\u30b9",
      "effect": "\u2460\uff1a\u304a\u4e92\u3044\u306e\u30d7\u30ec\u30a4\u30e4\u30fc\u306f\u3001\u30c7\u30c3\u30ad\u3092\u30b7\u30e3\u30c3\u30d5\u30eb\u3057\u3001\u30c7\u30c3\u30ad\u304b\u3089\uff11\u679a\u30c9\u30ed\u30fc\u3059\u308b\u3002\u305d\u306e\u5f8c\u3001\u304a\u4e92\u3044\u306e\u30d7\u30ec\u30a4\u30e4\u30fc\u306f\u624b\u672d\u3092\uff11\u679a\u9078\u3093\u3067\u6368\u3066\u308b\u3002"
    },
    "ko": {
      "name": "\ub51c\ub7ec\uc988 \ucd08\uc774\uc2a4",
      "effect": "\u2460: \uc591\ucabd \ud50c\ub808\uc774\uc5b4\ub294, \ub371\uc744 \uc154\ud50c\ud558\uace0, \ub371\uc5d0\uc11c 1\uc7a5 \ub4dc\ub85c\uc6b0\ud55c\ub2e4. \uadf8 \ud6c4, \uc591\ucabd \ud50c\ub808\uc774\uc5b4\ub294 \ud328\ub97c 1\uc7a5 \uace0\ub974\uace0 \ubc84\ub9b0\ub2e4."
    },
    "zh-TW": {
      "name": "\u838a\u5bb6\u9078\u64c7",
      "effect": "\u2460\uff1a\u96d9\u65b9\u73a9\u5bb6\u5c07\u724c\u7d44\u6d17\u724c\uff0c\u5f9e\u724c\u7d44\u62bd\uff11\u5f35\u724c\u3002\u5176\u5f8c\uff0c\u96d9\u65b9\u73a9\u5bb6\u9078\u64c7\uff11\u5f35\u624b\u724c\u6368\u68c4\u3002"
    },
    "zh-CN": {
      "name": "\u5e84\u5bb6\u9009\u62e9",
      "effect": "\u2460\uff1a\u53cc\u65b9\u73a9\u5bb6\u628a\u5361\u7ec4\u6d17\u5207\uff0c\u4ece\u5361\u7ec4\u62bd1\u5f20\u3002\u90a3\u4e4b\u540e\uff0c\u53cc\u65b9\u73a9\u5bb6\u90091\u5f20\u624b\u5361\u4e22\u5f03\u3002"
    }
  },
  "cardType": "trap",
  "subcategory": "normal",
  "passwords": [
    "89462956"
  ],
  "images": [
    {
      "id": "d4b551bc-0305-4dd9-9f93-a7fdf7861ded",
      "password": "89462956",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/89462956.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/89462956.jpg"
    }
  ],
  "sets": [
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "n",
    "craftable": true
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Dealer's Choice",
        "id": 557472
      }
    ],
    "dbID": 13796,
    "ygoprodeck": {
      "id": 89462956,
      "name": "dealer-s-choice-9471"
    },
    "yamlyugiID": 89462956
  },
  "series": []
}

=== iconmaster5326/YGOJSON/cards/4db482e2-d7dd-474c-9e1f-9f5af87afabe.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "4db482e2-d7dd-474c-9e1f-9f5af87afabe",
  "text": {
    "en": {
      "name": "Krawler Ranvier",
      "effect": "FLIP: You can target up to 2 \"Krawler\" monsters in your GY; add them to your hand.\nIf this face-up card in its owner's control leaves the field because of an opponent's card effect: You can Special Summon 2 \"Krawler\" monsters with different names from your Deck in face-down Defense Position, except \"Krawler Ranvier\". You can only use each effect of \"Krawler Ranvier\" once per turn."
    },
    "fr": {
      "name": "Ranvier Krawler",
      "effect": "FLIP : Vous pouvez cibler max. 2 monstres \"Krawler\" dans votre Cimeti\u00e8re ; ajoutez-les \u00e0 votre main.\nSi cette carte face recto contr\u00f4l\u00e9e par son propri\u00e9taire quitte le Terrain \u00e0 cause d'un effet de carte de l'adversaire : vous pouvez Invoquer Sp\u00e9cialement 2 monstres \"Krawler\" (\"Ranvier Krawler\" exclu) de noms diff\u00e9rents depuis votre Deck en Position de D\u00e9fense face verso. Vous ne pouvez utiliser chaque effet de \"Ranvier Krawler\" qu'une fois par tour."
    },
    "de": {
      "name": "Krawler Ranvier",
      "effect": "FLIPP: Du kannst bis zu 2 \u201eKrawler\u201c-Monster in deinem Friedhof w\u00e4hlen; f\u00fcge sie deiner Hand hinzu.\nFalls diese offene Karte, die ihr Besitzer kontrolliert, das Spielfeld durch einen Karteneffekt eines Gegners verl\u00e4sst: Du kannst 2 \u201eKrawler\u201c-Monster mit unterschiedlichen Namen als Spezialbeschw\u00f6rung von deinem Deck in die verdeckte Verteidigungsposition beschw\u00f6ren, au\u00dfer \u201eKrawler Ranvier\u201c. Du kannst jeden Effekt von \u201eKrawler Ranvier\u201c nur einmal pro Spielzug verwenden."
    },
    "it": {
      "name": "Krawler Ranvier",
      "effect": "SCOPRI: Puoi scegliere come bersaglio fino a 2 mostri \"Krawler\" nel tuo Cimitero; aggiungili alla tua mano.\nSe questa carta scoperta sotto il controllo del suo proprietario lascia il Terreno a causa dell'effetto di una carta dell'avversario: puoi Evocare Specialmente 2 mostri \"Krawler\" con nomi diversi dal tuo Deck coperti in Posizione di Difesa, eccetto \"Krawler Ranvier\". Puoi utilizzare ogni effetto di \"Krawler Ranvier\" una sola volta per turno."
    },
    "pt": {
      "name": "Ranvier Krawler",
      "effect": "VIRE: Voc\u00ea pode escolher at\u00e9 2 monstros \"Krawler\" no seu Cemit\u00e9rio; adicione-os \u00e0 sua m\u00e3o.\nSe este card com a face para cima sob o controle do seu dono deixar o campo devido a um efeito de card do oponente: voc\u00ea pode Invocar por Invoca\u00e7\u00e3o-Especial 2 monstros \"Krawler\" com nomes diferentes do seu Deck em Posi\u00e7\u00e3o de Defesa com a face para baixo, exceto \"Ranvier Krawler\". Voc\u00ea s\u00f3 pode usar cada efeito de \"Ranvier Krawler\" uma vez por turno."
    },
    "es": {
      "name": "Krawler Ranvier",
      "effect": "VOLTEO: Puedes seleccionar hasta 2 monstruos \"Krawler\" en tu Cementerio; a\u00f1\u00e1delos a tu mano.\nSi esta carta boca arriba en control de su due\u00f1o deja el Campo por efecto de una carta de un adversario: puedes Invocar de Modo Especial, desde tu Deck, 2 monstruos \"Krawler\" con nombres diferentes, en Posici\u00f3n de Defensa boca abajo, excepto \"Krawler Ranvier\". S\u00f3lo puedes usar cada efecto de \"Krawler Ranvier\" una vez por turno."
    },
    "ja": {
      "name": "\u30af\u30ed\u30fc\u30e9\u30fc\u30fb\u30e9\u30f3\u30f4\u30a3\u30a8",
      "effect": "\u3053\u306e\u30ab\u30fc\u30c9\u540d\u306e\u2460\u2461\u306e\u52b9\u679c\u306f\u305d\u308c\u305e\u308c\uff11\u30bf\u30fc\u30f3\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002\u2460\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u304c\u30ea\u30d0\u30fc\u30b9\u3057\u305f\u5834\u5408\u3001\u81ea\u5206\u306e\u5893\u5730\u306e\u300c\u30af\u30ed\u30fc\u30e9\u30fc\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\u3092\uff12\u4f53\u307e\u3067\u5bfe\u8c61\u3068\u3057\u3066\u767a\u52d5\u3067\u304d\u308b\u3002\u305d\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u3092\u624b\u672d\u306b\u52a0\u3048\u308b\u3002\u2461\uff1a\u8868\u5074\u8868\u793a\u306e\u3053\u306e\u30ab\u30fc\u30c9\u304c\u76f8\u624b\u306e\u52b9\u679c\u3067\u30d5\u30a3\u30fc\u30eb\u30c9\u304b\u3089\u96e2\u308c\u305f\u5834\u5408\u306b\u767a\u52d5\u3067\u304d\u308b\u3002\u300c\u30af\u30ed\u30fc\u30e9\u30fc\u30fb\u30e9\u30f3\u30f4\u30a3\u30a8\u300d\u4ee5\u5916\u306e\u300c\u30af\u30ed\u30fc\u30e9\u30fc\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\uff12\u4f53\u3092\u30c7\u30c3\u30ad\u304b\u3089\u88cf\u5074\u5b88\u5099\u8868\u793a\u3067\u7279\u6b8a\u53ec\u559a\u3059\u308b\uff08\u540c\u540d\u30ab\u30fc\u30c9\u306f\uff11\u679a\u307e\u3067\uff09\u3002"
    },
    "ko": {
      "name": "\ud06c\ub864\ub7ec \ub791\ube44\uc5d0",
      "effect": "\uc774 \uce74\ub4dc\uc758 \u2460\u2461\uc758 \ud6a8\uacfc\ub294 \uac01\uac01 1\ud134\uc5d0 1\ubc88\ubc16\uc5d0 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\ub2e4. \u2460 : \uc774 \uce74\ub4dc\uac00 \ub9ac\ubc84\uc2a4\ud588\uc744 \uacbd\uc6b0, \uc790\uc2e0\uc758 \ubb18\uc9c0\uc758 \"\ud06c\ub864\ub7ec\" \ubaac\uc2a4\ud130\ub97c 2\uc7a5\uae4c\uc9c0 \ub300\uc0c1\uc73c\ub85c \ud558\uace0 \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \uadf8 \ubaac\uc2a4\ud130\ub97c \ud328\uc5d0 \ub123\ub294\ub2e4. \u2461 : \uc55e\uba74 \ud45c\uc2dc\uc758 \uc774 \uce74\ub4dc\uac00 \uc0c1\ub300 \ud6a8\uacfc\ub85c \ud544\ub4dc\uc5d0\uc11c \ubc97\uc5b4\ub0ac\uc744 \uacbd\uc6b0\uc5d0 \ubc1c\ub3d9\ud560 \uc218 \uc788\ub2e4. \"\ud06c\ub864\ub7ec \ub791\ube44\uc5d0\" \uc774\uc678\uc758 \"\ud06c\ub864\ub7ec\" \ubaac\uc2a4\ud130 2\uc7a5\uc744 \ub371\uc5d0\uc11c \ub4b7\uba74 \uc218\ube44 \ud45c\uc2dc\ub85c \ud2b9\uc218 \uc18c\ud658\ud55c\ub2e4(\uac19\uc740 \uc774\ub984\uc758 \uce74\ub4dc\ub294 1\uc7a5\uae4c\uc9c0)."
    },
    "zh-CN": {
      "name": "\u673a\u602a\u866b\u30fb\u5170\u6c0f\u7ed3",
      "effect": "\u6b64\u5361\u540d\u7684\u2460\u2461\u6548\u679c1\u56de\u5408\u4ec5\u53ef\u5404\u4f7f\u75281\u6b21\u3002\u2460\uff1a\u6b64\u5361\u53cd\u8f6c\u7684\u60c5\u51b5\u4e0b\uff0c\u4ee5\u81ea\u5df1\u5893\u5730\u6700\u591a2\u53ea\u201c\u673a\u602a\u866b\u201d\u602a\u517d\u4e3a\u5bf9\u8c61\u53ef\u4ee5\u53d1\u52a8\u3002\u5c06\u8be5\u602a\u517d\u52a0\u5165\u624b\u724c\u3002\u2461\uff1a\u8868\u4fa7\u8868\u793a\u7684\u6b64\u5361\u56e0\u5bf9\u624b\u7684\u6548\u679c\u4ece\u573a\u4e0a\u79bb\u5f00\u7684\u60c5\u51b5\u4e0b\u53ef\u4ee5\u53d1\u52a8\u3002\u5c062\u53ea\u201c\u673a\u602a\u866b\u30fb\u5170\u6c0f\u7ed3\u201d\u4ee5\u5916\u7684\u201c\u673a\u602a\u866b\u201d\u602a\u517d\u4ece\u724c\u7ec4\u4ee5\u91cc\u4fa7\u5b88\u5907\u8868\u793a\u7279\u6b8a\u53ec\u5524\uff08\u540c\u540d\u5361\u6700\u591a1\u5f20\uff09\u3002"
    }
  },
  "cardType": "monster",
  "attribute": "earth",
  "type": "insect",
  "classifications": [
    "effect"
  ],
  "abilities": [
    "flip"
  ],
  "level": 2,
  "atk": 1100,
  "def": 900,
  "passwords": [
    "10698416"
  ],
  "images": [
    {
      "id": "0c06ec8c-8c9c-45dd-94a1-617568c8505a",
      "password": "10698416",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/10698416.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/10698416.jpg"
    }
  ],
  "sets": [
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "b4c2ad27-64e6-47af-8f72-d9461d8915f8",
    "9d106e04-53eb-4f3c-80f7-efc0b2433d45",
    "f3d792c7-f3ff-482e-bf07-9eaf178e7280",
    "4e3badf1-d1a1-4444-972b-223d53d1b3f2"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "n",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "n"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Krawler Ranvier",
        "id": 519678
      }
    ],
    "dbID": 13236,
    "ygoprodeck": {
      "id": 10698416,
      "name": "krawler-ranvier-8693"
    },
    "yamlyugiID": 10698416
  },
  "series": [
    "eaab5178-3cc7-4c12-9346-f9a49d022aa0"
  ]
}
